//
// Created by msmlab on 2025/11/14.
//

#include "config_manager.h"
#include <fstream>
#include <iostream>
#include <string>
#include <sstream>

ConfigManager& ConfigManager::getInstance() {
    static ConfigManager instance;
    return instance;
}

bool ConfigManager::loadFromFile(const std::string& config_path) {
    std::ifstream file(config_path);
    if (!file.is_open()) {
        std::cerr << "[ConfigManager] Failed to open config file: " << config_path << std::endl;
        return false;
    }

    std::string line;
    while (std::getline(file, line)) {
        // 跳过注释和空行
        if (line.empty() || line[0] == '#') {
            continue;
        }

        // 简单解析 key=value 格式
        size_t pos = line.find('=');
        if (pos == std::string::npos) {
            continue;
        }

        std::string key = line.substr(0, pos);
        std::string value = line.substr(pos + 1);

        // 去除前后空格
        key.erase(0, key.find_first_not_of(" \t"));
        key.erase(key.find_last_not_of(" \t") + 1);
        value.erase(0, value.find_first_not_of(" \t"));
        value.erase(value.find_last_not_of(" \t") + 1);

        // 根据key设置配置值
        if (key == "serial_port") {
            config_.serial_port = value;
        } else if (key == "serial_baudrate") {
            config_.serial_baudrate = std::stoi(value);
        } else if (key == "imu_serial_port") {
            config_.imu_serial_port = value;
        } else if (key == "mqtt_server_address") {
            config_.mqtt_server_address = value;
        } else if (key == "mqtt_client_id") {
            config_.mqtt_client_id = value;
        } else if (key == "mqtt_qos") {
            config_.mqtt_qos = std::stoi(value);
        } else if (key == "mocap_ip") {
            config_.mocap_ip = value;
        } else if (key == "mocap_target_name") {
            config_.mocap_target_name = value;
        } else if (key == "mocap_target_id") {
            config_.mocap_target_id = std::stoi(value);
        } else if (key == "mocap_dock_id") {
            config_.mocap_dock_id = std::stoi(value);
        } else if (key == "mocap_self_id") {
            config_.mocap_self_id = std::stoi(value);
        } else if (key == "control_loop_period_ms") {
            config_.control_loop_period_ms = std::stoi(value);
        } else if (key == "mqtt_send_interval") {
            config_.mqtt_send_interval = std::stoi(value);
        } else if (key == "lead_screw_z_init_pos") {
            config_.lead_screw_z_init_pos = std::stoi(value);
        } else if (key == "angle_tolerance_deg") {
            config_.angle_tolerance_deg = std::stod(value);
        } else if (key == "yaw_tolerance_deg") {
            config_.yaw_tolerance_deg = std::stod(value);
        }
    }

    std::cout << "[ConfigManager] Configuration loaded from: " << config_path << std::endl;
    return true;
}

const SystemConfig& ConfigManager::getConfig() const {
    return config_;
}

bool ConfigManager::saveToFile(const std::string& config_path) {
    std::ofstream file(config_path);
    if (!file.is_open()) {
        std::cerr << "[ConfigManager] Failed to create config file: " << config_path << std::endl;
        return false;
    }

    file << "# System Configuration\n";
    file << "# Generated by ConfigManager\n\n";

    file << "serial_port = " << config_.serial_port << "\n";
    file << "serial_baudrate = " << config_.serial_baudrate << "\n";
    file << "imu_serial_port = " << config_.imu_serial_port << "\n\n";

    file << "mqtt_server_address = " << config_.mqtt_server_address << "\n";
    file << "mqtt_client_id = " << config_.mqtt_client_id << "\n";
    file << "mqtt_qos = " << config_.mqtt_qos << "\n\n";

    file << "mocap_ip = " << config_.mocap_ip << "\n";
    file << "mocap_target_name = " << config_.mocap_target_name << "\n\n";
    file << "mocap_target_id = " << config_.mocap_target_id << "\n";
    file << "mocap_dock_id = " << config_.mocap_dock_id << "\n";
    file << "mocap_self_id = " << config_.mocap_self_id << "\n\n";

    file << "control_loop_period_ms = " << config_.control_loop_period_ms << "\n";
    file << "mqtt_send_interval = " << config_.mqtt_send_interval << "\n";
    file << "lead_screw_z_init_pos = " << config_.lead_screw_z_init_pos << "\n\n";

    file << "angle_tolerance_deg = " << config_.angle_tolerance_deg << "\n";
    file << "yaw_tolerance_deg = " << config_.yaw_tolerance_deg << "\n";

    file.flush();
    std::cout << "[ConfigManager] Configuration saved to: " << config_path << std::endl;
    return true;
}
